name: my first actions 

on: push

jobs: 
    first_job:
        runs-on: ubuntu-latest 
        steps:
         - name: checkout
           uses: actions/checkout@v4
           
         - name: welcome message 
           run: echo "this is my first github actions job"
         - name: list the files
           run: ls -la
         - name: Read me file
           run: cat README.md
         - name: run cowsay
           run: cowsay -f dragon "Here be dragons!"
