name: my first actions 

on: push

jobs: 
    first_job:
        runs-on: ubuntu-latest 
        steps:
         - name: checkout
           uses: actions/checkout@v4
         - name: run the script
           run |
             ls -lrt
             chmod +x ascii-script.sh
            ./ascii-script.sh
