name: creating ASCII artwork 

on: push

jobs:
 build_job_1:
  runs-on: ubuntu-latest
  steps:
  - name: install cowsay
    run: sudo  apt-get update && sudo apt-get install cowsay -y
  - name: execute cvowsay cmd 
    run: cowsay -f dragon "Run for cover, I am a DRAGON ....REAR" >>dragon.txt
  - name : sleep for 30 sec
    run: sleep 30

 test_job_2:
   needs:  build_job_1
   runs-on: ubuntu-latest
   steps:
   - name: sleep for 10 sec
     run: sleep 10

 deploy_job_3: 
   needs: test_job_2
   runs-on: ubuntu-latest
   steps:
   - name: test file exists
     run: cat dragon.txt
     